"""empty message

Revision ID: a44a0558978
Revises: 637498b5d88
Create Date: 2015-11-10 18:58:09.686645

"""

# revision identifiers, used by Alembic.
revision = 'a44a0558978'
down_revision = '637498b5d88'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_author',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=60),
               existing_nullable=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=25),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.String(length=25),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=80),
               existing_nullable=True)
    op.alter_column('user', 'is_author',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    ### end Alembic commands ###
